

# Stage 1
FROM node:14.18-alpine3.12 AS compile-image

WORKDIR /opt/app
# Enable the line below for local dev behind proxy
COPY .npmrc /opt/app
COPY package.json /opt/app
COPY package-lock.json /opt/app

COPY . /opt/app
RUN npm install

ENV PATH="./node_modules/.bin:$PATH"

RUN npm run build --prod

# Stage 2
FROM nginx
COPY src/main/docker/nginx/nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=compile-image /opt/app/target/classes/static /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
